baseurl = "https://echo3.co/"
languageCode = "en-us"
theme = "hugo-theme-terminal-extended"
paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  themeColor = "red"
  
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  
  # show selector to switch language
  showLanguageSelector = false
  
  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true
  
  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

[languages]
  [languages.en]
    title = "echo3.co"

    [languages.en.params]
	  subtitle = "Jude Sudbury, a freelance Swiss Army Knife IT professional for micro and small business"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      
	[languages.en.params.logo]
      logoText = "echo3.co"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      #[[languages.en.menu.main]]
       # identifier = "showcase"
       # name = "Showcase"
       # url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "services"
        url = "/portfolio"
	  [[languages.en.menu.main]]
        identifier = "blog"
        name = "blog"
        url = "/posts"
      #[[languages.en.menu.main]]
       # identifier = "linklist"
       # name = "Link List"
       # url = "/link-list"
